-
 text: Áreas de Prática
 text_en: Areas of Expertise
 link: /areas
-
 text: Equipa
 text_en: Team
 link: /equipa
- 
 text: Comunicação
 text_en: Communication
 link: /comunicacao
- 
 text: Recrutamento
 text_en: Recruitment
 link: /recrutamento
